package container;
import java.io.Serializable;

public class Student implements Serializable{
    // Todo
    /*
     * Define attributes for Student class with proper naming
     * Define constructor to initialize the value to instance variable
     */

    // make all the attribute public as we are storing it in a private database
    public String name;
    public int roll;
    public String section;
    public String branch;
    public long phoneNumber;
    public String address;
    public String dateOfAdmission; // AutoGenerated
    public long registrationNumber;


    public Student(String name,
            int roll,
            String section,
            String branch,
            long phoneNumber,
            String address,
            long registrationNumber) {

            // Todo initialize instance variable
    }
}